# Generated by Django 2.0.4 on 2018-08-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdcInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='机房名字')),
                ('is_virtual', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否云主机')),
            ],
        ),
    ]
